# coding: utf-8

"""
    Houses of the Oireachtas Open Data APIs

    The Houses of the Oireachtas is providing these APIs to allow our datasets to be retrieved and reused as widely as possible. They are intended to be used in conjunction with https://data.oireachtas.ie, from where our datasets can be accessed directly. By using the APIs, users can make metadata queries to identify the specific data they require. New data are available through the API as soon as they are published.  Currently, https://data.oireachtas.ie contains data in XML format from the Official Report of the Houses of the Oireachtas (the \"debates\") and replies to Parliamentary Questions in XML files complying with the [Akoma Ntoso](http://akomantoso.org) schema, as well data in PDF format for Bills, Acts and other documents published by the Houses of the Oireachtas.  Files can be retrieved from https://data.oireachtas.ie by adding the URI fragment contained in the \"formats\" fields of the JSON documents returned by these APIs. At the moment only PDF and XML files are available directly from https://data.oireachtas.ie, but this will become the endpoint for direct access of all \"uri\" fields in the data queried through https://api.oireachtas.ie. We will also be making bulk downloads available through https://data.oireachtas.ie.  Please note the APIs are a work in progress. We are working on expanding the range of datasets we publish, and we are interested in hearing about how to make these APIs more useful and wide ranging. For these reasons, we welcome any feedback, suggestions and user stories to open.data@oireachtas.ie  Data published through these APIs are made available under the [Oireachtas (Open Data) PSI Licence](https://beta.oireachtas.ie/en/open-data/license/)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: open.data@oireachtas.ie
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse2004MemberMembership(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'parties': 'list[InlineResponse2004MemberMembershipParties]',
        'house': 'InlineResponse2004MemberMembershipHouse',
        'offices': 'list[InlineResponse2004MemberMembershipOffices]',
        'uri': 'str',
        'represents': 'list[InlineResponse2004MemberMembershipRepresents]',
        'date_range': 'InlineResponse2004MemberMembershipPartyDateRange'
    }

    attribute_map = {
        'parties': 'parties',
        'house': 'house',
        'offices': 'offices',
        'uri': 'uri',
        'represents': 'represents',
        'date_range': 'dateRange'
    }

    def __init__(self, parties=None, house=None, offices=None, uri=None, represents=None, date_range=None):  # noqa: E501
        """InlineResponse2004MemberMembership - a model defined in Swagger"""  # noqa: E501

        self._parties = None
        self._house = None
        self._offices = None
        self._uri = None
        self._represents = None
        self._date_range = None
        self.discriminator = None

        if parties is not None:
            self.parties = parties
        if house is not None:
            self.house = house
        if offices is not None:
            self.offices = offices
        if uri is not None:
            self.uri = uri
        if represents is not None:
            self.represents = represents
        if date_range is not None:
            self.date_range = date_range

    @property
    def parties(self):
        """Gets the parties of this InlineResponse2004MemberMembership.  # noqa: E501


        :return: The parties of this InlineResponse2004MemberMembership.  # noqa: E501
        :rtype: list[InlineResponse2004MemberMembershipParties]
        """
        return self._parties

    @parties.setter
    def parties(self, parties):
        """Sets the parties of this InlineResponse2004MemberMembership.


        :param parties: The parties of this InlineResponse2004MemberMembership.  # noqa: E501
        :type: list[InlineResponse2004MemberMembershipParties]
        """

        self._parties = parties

    @property
    def house(self):
        """Gets the house of this InlineResponse2004MemberMembership.  # noqa: E501


        :return: The house of this InlineResponse2004MemberMembership.  # noqa: E501
        :rtype: InlineResponse2004MemberMembershipHouse
        """
        return self._house

    @house.setter
    def house(self, house):
        """Sets the house of this InlineResponse2004MemberMembership.


        :param house: The house of this InlineResponse2004MemberMembership.  # noqa: E501
        :type: InlineResponse2004MemberMembershipHouse
        """

        self._house = house

    @property
    def offices(self):
        """Gets the offices of this InlineResponse2004MemberMembership.  # noqa: E501


        :return: The offices of this InlineResponse2004MemberMembership.  # noqa: E501
        :rtype: list[InlineResponse2004MemberMembershipOffices]
        """
        return self._offices

    @offices.setter
    def offices(self, offices):
        """Sets the offices of this InlineResponse2004MemberMembership.


        :param offices: The offices of this InlineResponse2004MemberMembership.  # noqa: E501
        :type: list[InlineResponse2004MemberMembershipOffices]
        """

        self._offices = offices

    @property
    def uri(self):
        """Gets the uri of this InlineResponse2004MemberMembership.  # noqa: E501


        :return: The uri of this InlineResponse2004MemberMembership.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this InlineResponse2004MemberMembership.


        :param uri: The uri of this InlineResponse2004MemberMembership.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def represents(self):
        """Gets the represents of this InlineResponse2004MemberMembership.  # noqa: E501


        :return: The represents of this InlineResponse2004MemberMembership.  # noqa: E501
        :rtype: list[InlineResponse2004MemberMembershipRepresents]
        """
        return self._represents

    @represents.setter
    def represents(self, represents):
        """Sets the represents of this InlineResponse2004MemberMembership.


        :param represents: The represents of this InlineResponse2004MemberMembership.  # noqa: E501
        :type: list[InlineResponse2004MemberMembershipRepresents]
        """

        self._represents = represents

    @property
    def date_range(self):
        """Gets the date_range of this InlineResponse2004MemberMembership.  # noqa: E501


        :return: The date_range of this InlineResponse2004MemberMembership.  # noqa: E501
        :rtype: InlineResponse2004MemberMembershipPartyDateRange
        """
        return self._date_range

    @date_range.setter
    def date_range(self, date_range):
        """Sets the date_range of this InlineResponse2004MemberMembership.


        :param date_range: The date_range of this InlineResponse2004MemberMembership.  # noqa: E501
        :type: InlineResponse2004MemberMembershipPartyDateRange
        """

        self._date_range = date_range

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2004MemberMembership, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2004MemberMembership):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
